name: bhima_collect
description: A BHIMA mobile application for handling stock offline

publish_to: 'none' 

version: 1.0.1+10

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite:
  path:
  http:
  shared_preferences: ^2.0.15
  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.13.1
  flutter_form_builder: ^9.1.1
  form_builder_validators: ^9.1.0
  provider: ^6.0.3
  uuid: ^4.1.0
  flutter_offline: ^3.0.0
  date_format: ^2.0.6
  flutter_typeahead: ^4.0.0
  darq: ^2.0.0
  animated_splash_screen: ^1.3.0
  connectivity_plus: ^5.0.2
  getwidget: ^4.0.0
  flutter_toastify: ^1.0.4
  rflutter_alert: ^2.0.7
  internet_connection_checker: ^1.0.0+1
  money_formatter: ^0.0.5
  flutter_localizations:
    sdk: flutter
  intl: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
